plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance
  - rubocop-packaging

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  Max: 30

RSpec/MultipleExpectations:
  Max: 5

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/ExampleLength:
  Max: 10
